services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: bas
      MONGO_INITDB_ROOT_PASSWORD: bas
      MONGO_INITDB_DATABASE: mydb
